OPT MODULE

EXPORT ENUM  MXCMD_INIT=1001,
             MXCMD_END,
             MXCMD_PLAYCHANNEL,
             MXCMD_STOPCHANNEL,
             MXCMD_STOPCHANNELMASK,
             MXCMD_FREECHANNELS,
             MXCMD_SETFREQUENCY,
             MXCMD_SETVOLUME
